# Usa a imagem oficial do Node.js
FROM node:22

# Define diretório de trabalho
WORKDIR /app

# Copia package.json e instala dependências
COPY package*.json ./
RUN npm install

# Copia o restante do projeto
COPY . .

# Expõe a porta padrão do Next.js
EXPOSE 3000

# Rodar o Next.js em modo dev
CMD ["npm", "run", "dev"]
